# Limit the Gradle daemon heap
org.gradle.jvmargs=-Xmx512m

# Framework versions - single source of truth for all modules
# these versions are used in the dependency management plugin configuration so they need to be here, rather than ext
# every time we change these versions, we need to check the BOM and update the ext.versions as well.
# BOM: https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
# BOM repo: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/{version}/spring-boot-dependencies-{version}.pom
springBootVersion=4.1.0-M4
dependencyManagementVersion=1.1.7
